"""Application-level validation of provider results.

Pydantic enforces structure (types, enums, list caps, extra-field rejection); this
module enforces the *content* rules of the product framing:

- every non-empty quotation must actually occur in the target paragraph
  (fabricated evidence is rejected);
- occurrence indices must be consistent with the real occurrence count;
- no authorship claims or probabilities, in any free-text field;
- no detector-evasion or intentional-error advice;
- short paragraphs may never carry a ``moderate``/``strong`` standalone signal;
- the result scope must match what was requested;
- the limitations note is mandatory.

Validation issues are messages *about* the result, safe to log — they must never
embed document text or provider prose. Each issue carries a stable ``code`` used by
tests and by the repair prompt.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

from isai.models import ReviewResult, Scope, StyleSignal
from isai.textmatch import contains_quote, occurrence_count, word_count


class IssueCode(StrEnum):
    SCOPE_MISMATCH = "scope_mismatch"
    SHORT_PARAGRAPH_SIGNAL = "short_paragraph_signal"
    MISSING_LIMITATIONS_NOTE = "missing_limitations_note"
    FABRICATED_EVIDENCE = "fabricated_evidence"
    BAD_OCCURRENCE_INDEX = "bad_occurrence_index"
    AUTHORSHIP_CLAIM = "authorship_claim"
    EVASION_ADVICE = "evasion_advice"
    REPLACEMENT_WITHOUT_TARGET = "replacement_without_target"


@dataclass(frozen=True)
class ValidationIssue:
    code: IssueCode
    field: str
    message: str  # log-safe: no document text, no provider prose


# --- Forbidden-language patterns -------------------------------------------------
# These scan provider prose. They are deliberately targeted at *claims about this
# text's authorship* and *evasion advice*; they must not fire on the permitted
# register ("AI-associated stylistic patterns", "manual review recommended").

_AUTHORSHIP_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE)
    for p in (
        # "was/is (likely/probably/...) written/generated by (an) AI/ChatGPT/a human"
        r"\b(?:was|were|is|are|has been|have been)\s+(?:\w+\s+){0,2}?"
        r"(?:written|generated|produced|authored|created|composed)\s+by\s+"
        r"(?:an?\s+)?(?:ai\b|a\.i\.|chatgpt|gpt[-\w]*|claude|gemini|copilot|llm|"
        r"language\s+model|machine|bot|human)",
        # "this paragraph/text/passage is AI-generated / machine-written"
        r"\b(?:this|the)\s+(?:paragraph|text|passage|section|document|essay|thesis)\s+"
        r"(?:was|is|appears\s+to\s+be|seems\s+to\s+be|is\s+likely|is\s+probably)\s+"
        r"(?:\w+\s+){0,2}?(?:ai|machine|chatgpt|llm)[-\s](?:generated|written|authored|produced)",
        # authorship probabilities: "85% chance/probability/likely (that it was) AI"
        r"\b\d{1,3}\s*(?:%|percent)\s*(?:chance|probability|likelihood|likely|certain|confident)",
        r"\bprobability\s+of\s+\d{1,3}\s*(?:%|percent)",
        # "the author used ChatGPT/AI"
        r"\bthe\s+author\s+(?:used|employed|relied\s+on)\s+"
        r"(?:an?\s+)?(?:ai\b|chatgpt|gpt[-\w]*|claude|gemini|llm)",
        # detector verdict language
        r"\b(?:definitely|certainly|clearly|obviously|undoubtedly)\s+"
        r"(?:ai|machine|human)[-\s](?:generated|written|authored)",
    )
)

_EVASION_PATTERNS: tuple[re.Pattern[str], ...] = tuple(
    re.compile(p, re.IGNORECASE)
    for p in (
        r"\b(?:evade|evading|avoid|avoiding|bypass|bypassing|fool|fooling|trick|"
        r"tricking|beat|beating|defeat|defeating)\s+(?:\w+\s+){0,2}?detect(?:ion|ors?)?",
        r"\bundetectable\b",
        r"\bmake\s+(?:it|this|the\s+text|the\s+writing)\s+(?:look|seem|appear|read|sound)\s+"
        r"(?:more\s+|less\s+)?(?:human|ai)",
        r"\b(?:deliberate|intentional)\s+(?:errors?|mistakes?|typos?|imperfections?)",
        r"\b(?:introduce|introducing|add|adding|insert|inserting|sprinkle|sprinkling)\s+"
        r"(?:a\s+few\s+|some\s+|random\s+|occasional\s+)?(?:errors?|typos?|mistakes?)",
        r"\bpass\s+(?:as|for)\s+human",
    )
)


def _prose_fields(result: ReviewResult) -> list[tuple[str, str]]:
    """All free-text fields subject to the forbidden-language scan."""
    fields: list[tuple[str, str]] = [
        ("summary", result.summary),
        ("limitations_note", result.limitations_note),
    ]
    for i, ind in enumerate(result.indicators):
        fields.append((f"indicators[{i}].explanation", ind.explanation))
    for i, ind in enumerate(result.counter_indicators):
        fields.append((f"counter_indicators[{i}].explanation", ind.explanation))
    for i, qi in enumerate(result.quality_issues):
        fields.append((f"quality_issues[{i}].description", qi.description))
    for i, co in enumerate(result.citation_observations):
        fields.append((f"citation_observations[{i}].observation", co.observation))
    for i, mc in enumerate(result.manual_checks):
        fields.append((f"manual_checks[{i}]", mc))
    for i, rs in enumerate(result.revision_suggestions):
        fields.append((f"revision_suggestions[{i}].issue", rs.issue))
        fields.append((f"revision_suggestions[{i}].recommended_change", rs.recommended_change))
        fields.append((f"revision_suggestions[{i}].reason", rs.reason))
        if rs.proposed_replacement is not None:
            fields.append(
                (f"revision_suggestions[{i}].proposed_replacement", rs.proposed_replacement)
            )
    return fields


def _quoted_fields(result: ReviewResult) -> list[tuple[str, str, int | None]]:
    """All (field, quotation, occurrence_index) triples that must occur in the target."""
    triples: list[tuple[str, str, int | None]] = []
    for i, ind in enumerate(result.indicators):
        triples.append((f"indicators[{i}].evidence", ind.evidence, ind.occurrence_index))
    for i, ind in enumerate(result.counter_indicators):
        triples.append((f"counter_indicators[{i}].evidence", ind.evidence, ind.occurrence_index))
    for i, qi in enumerate(result.quality_issues):
        triples.append((f"quality_issues[{i}].target_text", qi.target_text, qi.occurrence_index))
    for i, co in enumerate(result.citation_observations):
        triples.append(
            (f"citation_observations[{i}].target_text", co.target_text, co.occurrence_index)
        )
    for i, rs in enumerate(result.revision_suggestions):
        triples.append(
            (f"revision_suggestions[{i}].target_text", rs.target_text, rs.occurrence_index)
        )
    return triples


def _forbidden_language_issues(result: ReviewResult) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    for field, text in _prose_fields(result):
        if any(p.search(text) for p in _AUTHORSHIP_PATTERNS):
            issues.append(
                ValidationIssue(
                    IssueCode.AUTHORSHIP_CLAIM,
                    field,
                    "authorship claim or probability language is forbidden",
                )
            )
        if any(p.search(text) for p in _EVASION_PATTERNS):
            issues.append(
                ValidationIssue(
                    IssueCode.EVASION_ADVICE,
                    field,
                    "detector-evasion or intentional-error advice is forbidden",
                )
            )
    return issues


def validate_result(
    result: ReviewResult,
    *,
    target_text: str,
    requested_scope: Scope,
    min_words: int,
) -> list[ValidationIssue]:
    """Content validation of one provider result against its target paragraph."""
    issues: list[ValidationIssue] = []

    if result.scope is not requested_scope:
        issues.append(
            ValidationIssue(
                IssueCode.SCOPE_MISMATCH,
                "scope",
                f"result scope '{result.scope.value}' does not match requested "
                f"'{requested_scope.value}'",
            )
        )

    if (
        requested_scope is Scope.PARAGRAPH
        and word_count(target_text) < min_words
        and result.style_signal in (StyleSignal.MODERATE, StyleSignal.STRONG)
    ):
        issues.append(
            ValidationIssue(
                IssueCode.SHORT_PARAGRAPH_SIGNAL,
                "style_signal",
                f"standalone signal '{result.style_signal.value}' is not allowed for a "
                f"paragraph below the {min_words}-word threshold; use 'indeterminate'",
            )
        )

    if not result.limitations_note.strip():
        issues.append(
            ValidationIssue(
                IssueCode.MISSING_LIMITATIONS_NOTE,
                "limitations_note",
                "limitations_note is required and must be non-empty",
            )
        )

    for field, quote, occ in _quoted_fields(result):
        if not quote:
            continue
        if not contains_quote(target_text, quote):
            issues.append(
                ValidationIssue(
                    IssueCode.FABRICATED_EVIDENCE,
                    field,
                    "quoted text does not occur in the target paragraph",
                )
            )
            continue
        if occ is not None:
            count = occurrence_count(target_text, quote)
            if occ > count:
                issues.append(
                    ValidationIssue(
                        IssueCode.BAD_OCCURRENCE_INDEX,
                        field,
                        f"occurrence_index {occ} exceeds the {count} actual occurrence(s)",
                    )
                )

    issues.extend(_forbidden_language_issues(result))

    for i, rs in enumerate(result.revision_suggestions):
        if rs.proposed_replacement is not None and not rs.target_text:
            issues.append(
                ValidationIssue(
                    IssueCode.REPLACEMENT_WITHOUT_TARGET,
                    f"revision_suggestions[{i}].proposed_replacement",
                    "a proposed_replacement requires a non-empty target_text",
                )
            )

    return issues


def repair_instruction(issues: list[ValidationIssue]) -> str:
    """Concise, log-safe correction text for the single repair retry."""
    lines = [f"- {i.field}: {i.message} [{i.code.value}]" for i in issues]
    return (
        "The previous response violated the result contract. Return a corrected JSON "
        "object with the same schema. Problems to fix:\n" + "\n".join(lines)
    )
